# Generated by Django 5.1.2 on 2025-10-24 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_options_invoiceitem_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='clinic_name',
            field=models.CharField(default='عيادة سامي الطبية', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
