# Generated by Django 5.1.2 on 2025-10-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_clinic_name_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
