# Generated by Django 5.1.2 on 2025-10-22 09:07

import django.utils.timezone
import licensing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=licensing.models.generate_license_key, max_length=64, unique=True)),
                ('issued_to', models.CharField(blank=True, default='', max_length=255)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
            ],
        ),
    ]
