# Generated by Django 5.1.2 on 2025-10-28 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='licensekey',
            name='code',
        ),
        migrations.AddField(
            model_name='licensekey',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='key',
            field=models.CharField(default='TEMP-LICENSE', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
