# Generated by Django 5.1.2 on 2025-10-28 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_remove_licensekey_activated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=128, unique=True)),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='licensekey',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='licensekey',
            name='key',
        ),
    ]
