# Generated by Django 5.1.2 on 2025-10-29 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_usedlicense_remove_licensekey_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='allowed_devices',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='remaining_devices',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='signature',
            field=models.CharField(default='UNKNOWN', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_hash', models.CharField(max_length=255)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to='licensing.licensekey')),
            ],
            options={
                'unique_together': {('license', 'machine_hash')},
            },
        ),
    ]
