# Generated by Django 5.1.2 on 2025-10-22 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_patient_phone_alter_patient_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الموعد')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='الوقت')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب الزيارة')),
                ('status', models.CharField(choices=[('scheduled', 'قيد الانتظار'), ('completed', 'تمت الزيارة'), ('cancelled', 'ألغيت')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
