# Generated by Django 5.1.2 on 2025-10-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_remove_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
