# Generated by Django 5.1.2 on 2025-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_phone_alter_patient_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=10),
        ),
    ]
